pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./_build
      - ./deps
    volumes:
      - /tmp/cache:/cache

  build:
    image: bitwalker/alpine-elixir-phoenix
    commands:
      - mkdir -p priv/repo/migrations
      - mix local.hex --force
      - mix local.rebar --force
      - mix deps.get
      - mix test

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./_build
      - ./deps
    volumes:
      - /tmp/cache:/cache

services:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=phnx_db
